###### Configuration
homeassistant:
  name: " "
  whitelist_external_dirs:
  - /docker/database-home_assistant/
  - /config/
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 264
  unit_system: metric
  time_zone: !secret time_zone
  customize: !include_dir_merge_named customizations
  packages: !include_dir_named packages
################################################################################
frontend:
  themes: !include_dir_merge_named themes/
lovelace:
  mode: yaml
config:
python_script:
conversation:
map:
updater:
owntracks:
system_health:
person:
custom_updater:
  card_urls:
    - https://raw.githubusercontent.com/kalkih/mini-graph-card/master/tracker.json
    - https://raw.githubusercontent.com/kalkih/mini-media-player/master/tracker.json
history:
  include:
    domains:
      - light
      - switch
      - vacuum
      - script
    entities:
      - device_tracker.justin_justin
      - device_tracker.nicole_nicole
      - input_boolean.justin
      - input_boolean.nicole
      - input_boolean.vacation
      - input_boolean.guest
      - input_boolean.away
      - input_boolean.finn_sleep
      - sensor.dark_sky_apparent_temperature
      - sensor.dark_sky_temperature
      - sensor.dark_sky_cloud_coverage
      - sensor.dark_sky_dew_point
      - sensor.dark_sky_humidity
      - sensor.dining_room_lux
      - sensor.dining_room_motion
      - sensor.dining_room_temperature
      - sensor.findlay_room_lux
      - sensor.findlay_room_motion
      - sensor.findlay_room_temperature
      - sensor.living_room_lux
      - sensor.living_room_motion
      - sensor.living_room_temperature
      - sensor.glances_cpu_load
      - sensor.hallway_thermostat_humidity
      - sensor.hallway_thermostat_hvac_state
      - sensor.hallway_thermostat_operation_mode
      - sensor.hallway_thermostat_operation_mode
      - sensor.hallway_thermostat_target
      - sensor.hallway_thermostat_temperature
      - sensor.mold_indicator
      - sensor.office_current
      - sensor.office_draw
      - sensor.office_today
      - sensor.office_voltage
      - sensor.office_yesterday
      - sensor.server_yesterday
      - sensor.washing_machine_today_kwh
      - sensor.pws_uv
      - sensor.uv_burn_time
      - sun.sun

logbook:
sun:
# discovery:

zwave:
  usb_path: /dev/zwave

emulated_hue:
  host_ip: !secret emulated_hue_url
  expose_by_default: false

logger:
  #default: warning
  default: error
  #default: info
  logs:
    homeassistant.components.switch.command_line: fatal
    homeassistant.components.sensor.command_line: fatal
    homeassistant.components.sensor.template: fatal
    homeassistant.components.switch.template: fatal
    homeassistant.components.camera.generic: fatal
    homeassistant.components.camera.mjpeg: fatal
    pychromecast.socket_client: fatal
    pydroid_ipcam: fatal

http:
   base_url: !secret base_url
   api_password: !secret api_password
   ssl_certificate: !secret ssl_certificate
   ssl_key: !secret ssl_key
   ssl_profile: intermediate
   ip_ban_enabled: True
   login_attempts_threshold: 3

duckdns:
   domain: !secret domain
   access_token: !secret access_token

tts:
  platform: google

recorder:
  db_url: !secret database
  purge_interval: 10
  purge_keep_days: 10

hue:
  bridges:
    - host: !secret philips_hue_ip

tplink:
  discovery: false
  light:
    - host: 192.168.1.108
  switch:
    - host: 192.168.1.211

mqtt:
  broker: !secret mqtt_url
  port: !secret mqtt_port
  client_id: !secret mqtt_client_id
  keepalive: 60
  username: !secret mqtt_user
  password: !secret mqtt_password
  discovery: true
  discovery_prefix: homeassistant

device_tracker:
  - platform: ping
    hosts:
      philips_hue_hub: 192.168.1.13
      skullcanyon: 192.168.1.115
      roomba: 192.168.1.147
      router: 192.168.1.1
      camera_baby: 192.168.1.92
      seed_box: 192.168.1.93
  - platform: unifi
    username: !secret unifi_user
    password: !secret unifi_password
    verify_ssl: false

wemo:
  static:
    - 192.168.1.200
    - 192.168.1.201
    - 192.168.1.202
    - 192.168.1.203
    - 192.168.1.204
    - 192.168.1.205
    - 192.168.1.206
cast:
  media_player:
  - host: 192.168.1.230
  - host: 192.168.1.231
  - host: 192.168.1.232
  - host: 192.168.1.235
  - host: 192.168.1.119
  - host: 192.168.1.143
  - host: 192.168.1.185

media_player:
  - platform: kodi
    host: !secret kodi_livingroom_ip
    port: !secret kodi_livingroom_port
    username: !secret kodi_livingroom_username
    password: !secret kodi_livingroom_password
    enable_websocket: false
    turn_off_action:
      service: media_player.kodi_call_method
      data_template:
        entity_id: '{{ entity_id }}'
        method: System.Shutdown
    name: kodi_livingroom
