################################################################
## Packages / Backyard
################################################################
homeassistant:
  customize:
    switch.sonoff_1:
      friendly_name: Patio Amplifier
      icon: mdi:amplifier

# ###### AUTOMATIC CONTROL OF AMPLIFIER
automation:
  - alias: "Backyard Amp Off"
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: media_player.backyard
        to: 'idle'
        for:
          minutes: 1
      - platform: state
        entity_id: media_player.backyard
        to: 'off'
      - platform: state
        entity_id: switch.sonoff_1
        from: 'on'
        to: 'off'
    action:
      - service: switch.turn_off
        entity_id: switch.sonoff_1
      - service: media_player.turn_off
        entity_id: media_player.backyard

  - alias: "Backyard Amp On"
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: media_player.backyard
        to: 'playing'
    action:
      - service: switch.turn_on
        entity_id: switch.sonoff_1
