################################################################
## Packages / Camera
################################################################
homeassistant:
   customize:
    script.notify_camera:
      friendly_name: Email Camera Photo

# zoneminder:
#   host: !secret zm_host
#   path: /zm/
#   username: !secret zm_username
#   password: !secret zm_password
android_ip_webcam:
  - host: !secret android_ip_webcam_host
    port: 8080
    name: driveway_wide
    sensors:
      - battery_level
      - battery_temp
      - motion
      - light
      - pressure
camera:
#  - platform: zoneminder

  - platform: mjpeg
    name: findlay
    mjpeg_url: !secret dlink_camera_link
    username: !secret dlink_camera_username
    password: !secret dlink_camera_password

  - platform: mjpeg
    name: driveway
    mjpeg_url: !secret dlink2_camera_mjpeg
    username: !secret dlink2_camera_username
    password: !secret dlink2_camera_password

automation:
  - alias: driveway_motion_detected
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.driveway_events
    condition:
      - condition: state
        entity_id: input_boolean.away
        state: 'on'
    action:
      - service: notify.discord
        data:
          message: "Motion Detected in the Driveway"
          target: !secret discord

script:
  notify_camera:
    sequence:
      - service: shell_command.clear_images
      - service: shell_command.driveway
      - service: shell_command.driveway2
      - delay: '00:00:30'
      - service: notify.discord
        data:
          target: !secret discord
          message: !secret notify_camera_message

# sensor:
#   - platform: zoneminder
#     include_archived: false

shell_command:
  clear_images: rm /config/www/camera_shots/*
  driveway: !secret driveway_camera_photo_url
  driveway2: curl -o /config/www/camera_shots/drive1.gif "127.0.0.1:3333/gif?camera=drive1&duration=60&interval=0.25"
