################################################################
## Packages / Digital Assistant
################################################################
homeassistant:
  customize:
    script.pc:
      emulated_hue_hidden: false
      friendly_name: 'PC'
    script.kodi_pause:
      emulated_hue_hidden: false
      friendly_name: 'pause'
    script.kodi_play:
      emulated_hue_hidden: false
      friendly_name: 'play'
    script.kodi_stop:
      emulated_hue_hidden: false
      friendly_name: 'stop'
    script.kodi_nav_select:
      emulated_hue_hidden: false
      friendly_name: 'select'
    script.kodi_next:
      emulated_hue_hidden: false
      friendly_name: 'next'
    script.kodi_previous:
      emulated_hue_hidden: false
      friendly_name: 'previous'
    script.kodi_nav_up:
      emulated_hue_hidden: false
      friendly_name: 'up'
    script.kodi_nav_down:
      emulated_hue_hidden: false
      friendly_name: 'down'
    script.kodi_nav_left:
      emulated_hue_hidden: false
      friendly_name: 'left'
    script.kodi_nav_right:
      emulated_hue_hidden: false
      friendly_name: 'right'

google_assistant:
  project_id: !secret google_assistant_project_id
  api_key: !secret google_assistant_api
  exposed_domains:
    - switch
  entity_config:
    script.pc:
      expose: true
      name: 'PC'
    switch.bedroom_fan:
      expose: True
      name: 'fan'
    input_boolean.finn_sleep:
      expose: True
      name: 'sleep'
    light.deck_lights:
      expose: true
      name: 'backyard lights'
    script.kodi_pause:
      expose: true
      name: 'pause'
    script.kodi_play:
      expose: true
      name: 'play'
    script.kodi_stop:
      expose: true
      name: 'stop'
    script.kodi_nav_select:
      expose: true
      name: 'select'
    script.kodi_next:
      expose: true
      name: 'next'
    script.kodi_previous:
      expose: true
      name: 'previous'
    script.kodi_nav_up:
      expose: true
      name: 'up'
    script.kodi_nav_down:
      expose: true
      name: 'down'
    script.kodi_nav_left:
      expose: true
      name: 'left'
    script.kodi_nav_right:
      expose: true
      name: 'right'

automation:
  - alias: 'google_home_volume'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_boolean.finn_sleep
    action:
    - service: media_player.volume_set
      data_template:
        entity_id: media_player.google_home
        volume_level: >
          {% if is_state('input_boolean.finn_sleep', 'on') %} 0.50
          {% elif is_state('input_boolean.finn_sleep', 'off') %} 1
          {% endif %}
script:
###### ALEXA TURN ON or OFF PC (Living Room)
  pc:
    sequence:
      - service: switch.toggle
        entity_id: switch.office_pc
