################################################################
## Packages / Doorbell
################################################################
homeassistant:
automation:
  - alias: 'doorbell'
    initial_state: 'on'
    trigger:
    - platform: event
      event_type: zha_event
      event_data:
        unique_id: '0xf0c1:1:0x0006'
        device_ieee: '00:15:8d:00:03:26:94:9a'
        command: 'attribute_updated'
    action:
    - service: media_player.volume_set
      data_template:
        entity_id: media_player.google_home
        volume_level: >
          {% if is_state('input_boolean.finn_sleep', 'off') %} 1
          {% elif is_state('input_boolean.finn_sleep', 'on') %} 0.40
          {% endif %}
    - service: media_player.play_media
      data_template:
        entity_id: media_player.google_home
        media_content_id: >
          http://192.168.1.115/doorbell_tones/
           {%- if is_state('input_select.theme', "New Year's Day") -%} new_years.mp3
           {%- elif is_state('input_select.theme', "Groundhog Day") -%} groundhog_day.mp3
           {%- elif is_state('input_select.theme', "Valentine's Day") -%} valentines_day.mp3
           {%- elif is_state('input_select.theme', "St. Patrick's Day") -%} door_1.mp3
           {%- elif is_state('input_select.theme', "Good Friday") -%} door_1.mp3
           {%- elif is_state('input_select.theme', "Starwars Day") -%} R2D2.mp3
           {%- elif is_state('input_select.theme', "Easter Sunday") -%} door_1.mp3
           {%- elif is_state('input_select.theme', "Earth Day") -%} door_1.mp3
           {%- elif is_state('input_select.theme', "Mother's Day") -%} door_1.mp3
           {% elif is_state('input_select.theme', "Victoria Day") -%} door_1.mp3
           {%- elif is_state('input_select.theme', "Father's Day") -%} get-to-the-choppa.mp3
           {%- elif is_state('input_select.theme', "Canada Day") -%}  door_1.mp3
           {%- elif is_state('input_select.theme', "Labour Day") -%} door_1.mp3
           {%- elif is_state('input_select.theme', "Thanksgiving Day") -%} door_1.mp3
           {%- elif is_state('input_select.theme', "Halloween") -%} halloween.wav
           {%- elif is_state('input_select.theme', "Remembrance Day") -%} door_1.mp3
           {%- elif is_state('input_select.theme', "Christmas Eve") -%} xmas.mp3
           {%- elif is_state('input_select.theme', "Christmas Day") -%} xmas.mp3
           {%- elif is_state('input_select.theme', "Boxing Day") -%} xmas.mp3
           {%- elif is_state('input_select.theme', "New Year's Eve") -%} new_years.mp3
           {%- else -%} door_1.mp3
           {%- endif -%}
        media_content_type: 'audio/mp3'

##############
  # - alias: 'guard dog'
  #   initial_state: 'on'
  #   trigger:
  #     - platform: state
  #       entity_id: binary_sensor.front_doorbell
  #       from: 'off'
  #       to: 'on'
  #   condition:
  #     condition: or
  #     conditions:
  #       - condition: state
  #         entity_id: 'input_boolean.away'
  #         state: 'on'
  #       - condition: state
  #         entity_id: 'input_boolean.vacation'
  #         state: 'on'
  #   action:
  #     - service: media_player.volume_set
  #       data:
  #         entity_id: media_player.google_home
  #         volume_level: 1.00
  #     - service: media_player.play_media
  #       data_template:
  #         entity_id: media_player.google_home
  #         media_content_id: "http://192.168.1.115/misc_sound/dog-barking-2-bullmastiff.mp3"
  #         media_content_type: 'audio/mp3'
  #     - service: notify.html5
  #       data:
  #         message: 'Someone is at the front door, Release the Hounds!'

sensor:
  - platform: template
    sensors:
      theme_sound:
        friendly_name: 'Doorbell Sound'
        value_template: >
           {%- if is_state('input_select.theme', "New Year's Day") -%} new_years.mp3
           {%- elif is_state('input_select.theme', "Groundhog Day") -%} groundhog_day.mp3
           {%- elif is_state('input_select.theme', "Valentine's Day") -%} valentines_day.mp3
           {%- elif is_state('input_select.theme', "St. Patrick's Day") -%} door_1.mp3
           {%- elif is_state('input_select.theme', "Good Friday") -%} door_1.mp3
           {%- elif is_state('input_select.theme', "Starwars Day") -%} R2D2.mp3
           {%- elif is_state('input_select.theme', "Easter Sunday") -%} door_1.mp3
           {%- elif is_state('input_select.theme', "Earth Day") -%} door_1.mp3
           {%- elif is_state('input_select.theme', "Mother's Day") -%} door_1.mp3
           {% elif is_state('input_select.theme', "Victoria Day") -%} door_1.mp3
           {%- elif is_state('input_select.theme', "Father's Day") -%} get-to-the-choppa.mp3
           {%- elif is_state('input_select.theme', "Canada Day") -%}  door_1.mp3
           {%- elif is_state('input_select.theme', "Labour Day") -%} door_1.mp3
           {%- elif is_state('input_select.theme', "Thanksgiving Day") -%} door_1.mp3
           {%- elif is_state('input_select.theme', "Halloween") -%} halloween.wav
           {%- elif is_state('input_select.theme', "Remembrance Day") -%} door_1.mp3
           {%- elif is_state('input_select.theme', "Christmas Eve") -%} xmas.mp3
           {%- elif is_state('input_select.theme', "Christmas Day") -%} xmas.mp3
           {%- elif is_state('input_select.theme', "Boxing Day") -%} xmas.mp3
           {%- elif is_state('input_select.theme', "New Year's Eve") -%} new_years.mp3
           {%- else -%} door_1.mp3
           {%- endif -%}
        icon_template: "{% if is_state('sun.sun', 'above_horizon') %}mdi:speaker-wireless{% else %}mdi:speaker{% endif %}"
