################################################################
## Packages / Good Night
################################################################
homeassistant:
  customize:
    script.good_night:
      emulated_hue_hidden: false
      emulated_hue_name: "Good Night"
      google_assistant: true
      google_assistant_name: "Good Night"
      friendly_name: Good Night
      icon: mdi:sleep

google_assistant:
  entity_config:
    script.good_night:
      expose: true
      name: 'Good Night'

script:
  good_night:
    sequence:
    - condition: time
      after: '20:30:00'
      before: '00:00:00'
    - service: light.turn_off
      entity_id: light.front_door
###### HALLWAY
    - service: light.turn_off
      entity_id: light.hallway
##### Master BEDROOM
    - service: switch.turn_off
      entity_id: switch.bedroom_media
    - service: switch.turn_off
      entity_id: switch.bedroom_lamps
    - service: switch.turn_on
      entity_id: switch.bedroom_fan
    - service: switch.turn_on
      entity_id: switch.white_noise
###### LIVINGROOM/KITCHEN
    - service: light.turn_off
      entity_id: light.living_room
    - service: light.turn_off
      entity_id: light.kitchen_sink
    - service: switch.turn_off
      entity_id: switch.tv
    - service: switch.turn_off
      entity_id: switch.receiver
    - service: script.nightlight
###### BACKYARD
    - service: light.turn_off
      entity_id: light.deck_lights
    - service: media_player.turn_off
      entity_id: media_player.backyard
    - service: switch.turn_off
      entity_id: switch.patio_amplifier
###### OFFICE
    - service: light.turn_off
      entity_id: light.aurora
    - service: switch.turn_off
      entity_id: switch.office_lightswitch
