################################################################
## Packages / Nest
################################################################
homeassistant:
  customize:
#Nest Thermostat
    binary_sensor.hallway_thermostat_fan:
      friendly_name: Thermostat Fan
      icon: mdi:fan
    sensor.hallway_thermostat_humidity:
      friendly_name: Hallway Humidity
      icon: mdi:water-percent
    sensor.hallway_thermostat_temperature:
      friendly_name: Hallway
    sensor.hallway_thermostat_hvac_state:
      friendly_name: Thermostat HVAC State
    sensor.hallway_thermostat_operation_mode:
      friendly_name: Thermostat Operation Mode
#Nest Protect
    sensor.kitchen_nest_protect_co_status:
      entity_picture: /local/custom_icons/nestprotect.png
    sensor.kitchen_nest_protect_smoke_status:
      entity_picture: /local/custom_icons/nestprotect.png
    sensor.kitchen_nest_protect_battery_health:
      friendly_name: Kitchen Nest Protect Battery
      hidden: true
      icon: mdi:battery
#Script
    script.fan:
      emulated_hue_hidden: false
      emulated_hue_name: "fan"
      friendly_name: Turn Fan on
      icon: mdi:fan
    script.hotter:
      emulated_hue_hidden: false
      friendly_name: 'Hotter'
    script.colder:
      emulated_hue_hidden: false
      friendly_name: 'Colder'

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

script:
###### ALEXA TURN ON HOT / COLD / FAN
  hotter:
    sequence:
      - service: climate.set_temperature
        data_template:
          entity_id: climate.hallway
          temperature: "{{ (states.climate.hallway.attributes.current_temperature | float) +1 }}"
  colder:
    sequence:
      - service: climate.set_temperature
        data_template:
          entity_id: climate.hallway
          temperature: "{{ (states.climate.hallway.attributes.current_temperature | float) -1 }}"
  fan:
    sequence:
      - service: climate.set_fan_mode
        data:
          entity_id: climate.hallway
          fan_mode: 'on'

switch:
  - platform: template
    switches:
      nest_fan:
        value_template: >-
          {%-set fan = states.climate.hallway.attributes.fan_mode-%}
          {%-if fan == 'on' -%}
            on
          {%- else -%}
            off
          {%- endif -%}
        turn_on:
          service: climate.set_fan_mode
          data:
            entity_id: climate.hallway
            fan_mode: 'on'
        turn_off:
          service: climate.set_fan_mode
          data:
            entity_id: climate.hallway
            fan_mode: 'off'
      nest_away:
        value_template: >-
          {%-set away = states.climate.hallway.attributes.preset_mode-%}
          {%-if away == 'away' -%}
            on
          {%- else -%}
            off
          {%- endif -%}
        turn_on:
          service: climate.set_preset_mode
          data:
            entity_id: climate.hallway
            preset_mode: 'away'
        turn_off:
          service: climate.set_preset_mode
          data:
            entity_id: climate.hallway
            preset_mode: 'none'
input_text:
  # A variable to store Nest's current mode - used when we restore from away mode
  nest_mode:
    name: Heating/Cooling Mode

automation:
  ###### SET STATE WHEN WINDOWS TOGGLED
  - alias: 'nest_to_off_windows_open'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.kitchen_window
        from: 'off'
        to: 'on'
    action:
        # Save the current mode for Nest so we can restore it later
      - service: input_text.set_value
        data_template:
          entity_id: input_text.nest_mode
          value: '{{ states.climate.hallway.state }}'
      # Set Nest to Eco mode
      - service: climate.set_preset_mode
        data:
          entity_id: climate.hallway
          preset_mode: 'eco'
  - alias: 'nest_to_on_windows_closed'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.kitchen_window
        from: 'on'
        to: 'off'
    condition:
      condition: and
      conditions:
        # House is currently in eco mode
        - condition: template
          value_template: '{{ is_state_attr("climate.hallway", "preset_mode", "eco") }}'
        # The last state was successfully saved/set
        - condition: template
          value_template: '{{ states.input_text.nest_mode.state != "unknown" }}'
    action:
      # Restore Nest to the orgional mode
      - service: climate.set_hvac_mode
        data_template:
          entity_id: climate.hallway
          operation_mode: '{{ states.input_text.nest_mode.state }}'
  ###### Nest protect states are - ok warning emergency
  - alias: 'notify if nest protect is not ok'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.kitchen_nest_protect_co_status,sensor.kitchen_nest_protect_smoke_status
        to: 'emergency'
    action:
      - service: script.janet_speech_engine
        data:
          call_greeting: 1
          call_inform: 1
        data_template:
          CustomMessage: >-
            'Nest has detected Smoke or CO in the Kitchen.'
      - service: hue.hue_activate_scene
        data:
          group_name: "Living Room"
          scene_name: "Alarm"
sensor:
    - platform: template
      sensors:
# TEMPS
        nest_target_temperature:
          friendly_name: "Target Temperature"
          entity_id: climate.hallway
          unit_of_measurement: "째C"
          value_template: "{{states.climate.hallway.attributes.temperature}}"
        nest_current_temperature:
          friendly_name: "Current Temperature"
          entity_id: climate.hallway
          unit_of_measurement: "째C"
          value_template: "{{states.climate.hallway.attributes.current_temperature}}"
        nest_target_temp_high:
          friendly_name: "target_temp_high"
          entity_id: climate.hallway
          unit_of_measurement: "째C"
          value_template: "{{states.climate.hallway.attributes.target_temp_high}}"
        nest_target_temp_low:
          friendly_name: "target_temp_low"
          entity_id: climate.hallway
          unit_of_measurement: "째C"
          value_template: "{{states.climate.hallway.attributes.target_temp_low}}"
# MODES
        nest_operation_mode:
          friendly_name: "Operation Mode"
          entity_id: climate.hallway
          value_template: "{{states.climate.hallway.state}}"
        nest_away_mode:
          friendly_name: "Operation Mode"
          entity_id: climate.hallway
          value_template: "{{states.climate.hallway.attributes.away_mode}}"
