################################################################
## Packages / Nest
################################################################
homeassistant:
  customize:
#Nest Thermostat
    climate.hallway:
      friendly_name: Nest Thermostat
      entity_picture: /local/custom_icons/nest.png
    binary_sensor.hallway_thermostat_fan:
      friendly_name: Thermostat Fan
      icon: mdi:fan
    sensor.hallway_thermostat_humidity:
      friendly_name: Hallway Humidity
      icon: mdi:water-percent
    sensor.hallway_thermostat_temperature:
      friendly_name: Hallway
    sensor.hallway_thermostat_hvac_state:
      friendly_name: Thermostat HVAC State
    sensor.hallway_thermostat_operation_mode:
      friendly_name: Thermostat Operation Mode
#Nest Protect
    sensor.kitchen_nest_protect_co_status:
      entity_picture: /local/custom_icons/nestprotect.png
    sensor.kitchen_nest_protect_smoke_status:
      entity_picture: /local/custom_icons/nestprotect.png
    sensor.kitchen_nest_protect_battery_health:
      friendly_name: Kitchen Nest Protect Battery
      hidden: true
      icon: mdi:battery
#Script
    script.fan:
      emulated_hue_hidden: false
      emulated_hue_name: "fan"
      friendly_name: Turn Fan on
      icon: mdi:fan
    script.hotter:
      emulated_hue_hidden: false
      friendly_name: 'Hotter'
    script.colder:
      emulated_hue_hidden: false
      friendly_name: 'Colder'

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

script:
###### ALEXA TURN ON HOT / COLD / FAN
  hotter:
    sequence:
      - service: climate.set_temperature
        data_template:
          entity_id: climate.hallway
          temperature: "{{ (states.climate.hallway.attributes.current_temperature | float) +0.5 }}"
  colder:
    sequence:
      - service: climate.set_temperature
        data_template:
          entity_id: climate.hallway
          temperature: "{{ (states.climate.hallway.attributes.current_temperature | float) -0.5 }}"
  fan:
    sequence:
      - service: climate.set_fan_mode
        data:
          entity_id: climate.hallway
          fan_mode: 'on'

automation:
  ###### Nest protect states are - ok warning emergency
  - alias: 'notify if nest protect is not ok'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.kitchen_nest_protect_co_status,sensor.kitchen_nest_protect_smoke_status
        to: 'emergency'
    action:
      - service: script.janet_speech_engine
        data:
          call_greeting: 1
          call_inform: 1
        data_template:
          CustomMessage: >-
            'Nest has detected Smoke or CO in the Kitchen.'
      - service: hue.hue_activate_scene
        data:
          group_name: "Living Room"
          scene_name: "Alarm"

  # - alias: 'nest open a window'
  #   initial_state: 'on'
  #   trigger:
  #     - platform: state
  #       entity_id: sensor.weather_inside_vs_outside
  #       from: 'false'
  #       to: 'true'
  #   condition:
  #     - condition: state
  #       entity_id: climate.hallway
  #       state: 'cool'
  #   action:
  #     - service: notify.html5
  #       data:
  #         message: 'It is cooler outside then inside and the AC is on. You should open a window!'
  #     - service: automation.turn_off
  #       data:
  #         entity_id: automation.nest_open_a_window
  #     - delay: '01:00:00'
  #     - service: automation.turn_on
  #       data:
  #         entity_id: automation.nest_open_a_window
