################################################################
## Packages / internet_usage
## @norien - https://github.com/Norien/Home-Assistant-Config
################################################################
homeassistant:

sensor:
  - platform: unifigateway
    host: localhost
    username: !secret unifi_user
    password: !secret unifi_password
    monitored_conditions:
      - www
      - wlan
      - lan
      - wan
      - alerts
      - firmware
## BREAKOUT UNIFI FOR LOVELACE
  - platform: template
    sensors:
      unifi_gateway_www_rx:
        entity_id: sensor.unifi_gateway_www
        unit_of_measurement: 'kB/s'
        value_template: "{{ state_attr('sensor.unifi_gateway_www', 'rx_bytes-r') / 1000}}"
      unifi_gateway_www_tx:
        entity_id: sensor.unifi_gateway_www
        unit_of_measurement: 'kB/s'
        value_template: "{{ state_attr('sensor.unifi_gateway_www', 'tx_bytes-r') / 1000}}"
      unifi_gateway_www_cpu:
        entity_id: sensor.unifi_gateway_wan
        unit_of_measurement: '%'
        value_template: "{{states.sensor.unifi_gateway_wan.attributes['gw_system-stats']['cpu']}}"
      unifi_gateway_www_mem:
        entity_id: sensor.unifi_gateway_wan
        unit_of_measurement: '%'
        value_template: "{{states.sensor.unifi_gateway_wan.attributes['gw_system-stats']['mem']}}"
      unifi_gateway_lan_num_user:
        entity_id: sensor.unifi_gateway_lan
        unit_of_measurement: 'Users'
        value_template: "{{states.sensor.unifi_gateway_lan.attributes['num_user']}}"
      unifi_gateway_wlan_num_user:
        entity_id: sensor.unifi_gateway_wlan
        unit_of_measurement: 'Users'
        value_template: "{{states.sensor.unifi_gateway_wlan.attributes['num_user']}}"
  ###### SENSOR FOR SEEXBOX DELUGE
  - platform: deluge
    host: !secret deluge_host
    port: !secret deluge_port
    username: !secret deluge_user
    password: !secret deluge_pass
    monitored_variables:
      - 'current_status'
      - 'download_speed'
      - 'upload_speed'
  - platform: command_line
    command: 'cat /config/www/deluge_ip'
    name: 'SeedBox IP'
    scan_interval: 60
###### CERT DAYS LEFT
  - platform: command_line
    command: 'cat /config/www/ssl.txt'
    name: Certificate
    unit_of_measurement: Days
    scan_interval: 43200
###### EXTERNAL IP FOR NOTIFY
  - platform: rest
    resource: https://api.ipify.org/?format=json
    #resource: http://ip.jsontest.com
    name: external_ip
    value_template: '{{ value_json.ip }}'
    scan_interval: 14400
###### CUSTOM DATA USAGE PYTHON SCRIPT
  # - platform: ssh
  #   name: usage_test
  #   host: !secret skullcanyon_host
  #   username: !secret skullcanyon_user
  #   password: !secret skullcanyon_pass
  #   command: !secret internet_usage_test
  #   value_template: >-
  #     {{value.split("\r\n")[1]}}

  - platform: command_line
    command: !secret internet_usage
    name: 'usage'
    scan_interval: 21600
  - platform: template
    sensors:
      seedbox_vpn_status:
        friendly_name: "VPN Status"
        value_template: >
          {%-set nuc = states.sensor.external_ip.state-%}
          {%-set deluge = states.sensor.seedbox_ip.state-%}
          {%-if deluge==nuc-%}
            Disconnected
          {%-elif deluge==unknown or nuc==unknown-%}
            Unknown
          {%-else-%}
            Connected
          {%-endif-%}
        icon_template: "{% if icon == icon %}mdi:earth-box{% endif %}"
        entity_id:  sensor.usage, sensor.quote_of_the_day
      usage_downloaded:
        friendly_name: "Downloaded"
        value_template: "{{states.sensor.usage.state.split(',')[0]}}"
        unit_of_measurement: "GB"
        icon_template: "{% if icon == icon %}mdi:folder-download{% endif %}"
        entity_id:  sensor.usage, sensor.quote_of_the_day
      usage_uploaded:
        friendly_name: "Uploaded"
        value_template: "{{states.sensor.usage.state.split(',')[1]}}"
        unit_of_measurement: "GB"
        icon_template: "{% if icon == icon %}mdi:folder-upload{% endif %}"
        entity_id:  sensor.usage, sensor.quote_of_the_day
      usage_total_usage:
        friendly_name: "Total Bandwidth"
        value_template: "{{states.sensor.usage.state.split(',')[3]}}"
        unit_of_measurement: "GB"
        icon_template: "{% if icon == icon %}mdi:folder-star{% endif %}"
        entity_id:  sensor.usage, sensor.quote_of_the_day
      usage_days_remaining:
        friendly_name: "Billing Period"
        value_template: "{{states.sensor.usage.state.split(',')[6]}}"
        unit_of_measurement: "Days"
        icon_template: "{% if icon == icon %}mdi:calendar-clock{% endif %}"
        entity_id:  sensor.usage, sensor.quote_of_the_day

automation:
###### NOTIFY AND RESTART SEEDBOX IF VPN DISCONNECTS
  - alias: Notify Of VPN Disconnect
    initial_state: 'on'
    trigger:
      platform: state
      entity_id: sensor.seedbox_ip
    condition:
      - condition: template
        value_template: "{%-if states.sensor.seedbox_ip.state==states.sensor.external_ip.state-%}True{% else%}False{%endif%}"
    action:
      - service: notify.discord
        data:
          target: !secret discord
          message: 'SeedBox VPN Has Disconnected!'
      - service: persistent_notification.create
        data_template:
          title: VPN Disconnected
          message: "VPN has disconnected and SeedBox was restarted!"
          notification_id: VPN Disconnected
###### NOTIFY IF IP CHANGES
  - alias: Notify Of New External IP
    initial_state: 'on'
    trigger:
      platform: state
      entity_id: sensor.external_ip
    condition:
      - condition: template
        value_template: "{% if trigger.from_state and trigger.to_state %} True {% else %} False {% endif %}"
    action:
      - service: shell_command.update_godaddy
      - service: notify.discord
        data_template:
          target: !secret discord
          message: "Your External IP changed from {{ trigger.from_state.state }} to {{ trigger.to_state.state }}"

### SWITCH FOR DELUGE SEEXBOX
switch:
  platform: deluge
  host: !secret deluge_host
  port: !secret deluge_port
  username: !secret deluge_user
  password: !secret deluge_pass

shell_command:
  update_godaddy: /usr/bin/python3 /config/python_scripts/godaddy_ddns.py %/config/python_scripts/godaddy-ddns.config
