################################################################
## Packages / Night Light
################################################################
homeassistant:
  customize:
    automation.night_light:
      friendly_name: 'Night Light'
      icon: mdi:brightness-4

automation:
  - alias: 'Night Light'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.living_room_sensor_motion, binary_sensor.dining_room_sensor_motion
        to: 'True'
    condition:
      - condition: state
        entity_id: 'sun.sun'
        state: 'below_horizon'
      - condition: state
        entity_id: 'input_boolean.vacation'
        state: 'off'
      - condition: state
        entity_id: 'input_boolean.away'
        state: 'off'
      - condition: time
        after: '20:00:00'
        before: '08:00:00'
      - condition: state
        entity_id: 'light.living_room'
        state: 'off'
      - condition: state
        entity_id: 'media_player.kodi_livingroom'
        state: 'idle'
    action:
      - service: script.turn_off
        data:
          entity_id: script.nightlight
      - service: script.turn_on
        data:
          entity_id: script.nightlight

script:
  nightlight:
    sequence:
      - service: light.turn_on
        data:
          entity_id:
            - light.kitchen_sink
            - light.living_room_lamp
            - light.hue_color_lamp_1
            - light.hue_color_lamp_3
          brightness: 10
          rgb_color: [255,104,18]
      - delay:
          minutes: 4
      - service_template: >
          {% if is_state_attr('light.living_room', 'rgb_color', (255, 104, 21)) %}
            script.nightlight_off
          {% else %}
            script.nightlight
          {% endif %}

  nightlight_off:
    sequence:
      - service: light.turn_off
        data:
          entity_id:
            - light.hue_color_lamp_1
            - light.hue_color_lamp_3
            - light.kitchen_sink
            - light.living_room_lamp
