################################################################
## Packages / Notifications
################################################################

notify:
  - platform: discord
    name: discord
    token: !secret discord_token
automation:
###### NOTIFY IF NICOLE HAS LEFT ONE OF HER WORKPLACES
  - alias: Notify If Left Work
    initial_state: 'on'
    trigger:
      - platform: zone
        entity_id: device_tracker.nicole_nicole
        zone: zone.work_whitehills
        event: leave
      - platform: zone
        entity_id: device_tracker.nicole_nicole
        zone: zone.work_westmount
        event: leave
      - platform: zone
        entity_id: device_tracker.nicole_nicole
        zone: zone.work_old_south
        event: leave
      - platform: zone
        entity_id: device_tracker.nicole_nicole
        zone: zone.victoria_hospital
        event: leave
      - platform: zone
        entity_id: device_tracker.nicole_nicole
        zone: zone.daycare
        event: leave
    action:
      - service: notify.discord
        data_template:
          target: !secret discord
          message: >
            {{ trigger.to_state.attributes.friendly_name }} has left {{ trigger.zone.attributes.friendly_name }}
      - service: script.janet_speech_engine
        data:
          call_greeting: 1
        data_template:
          CustomMessage: >
            {{ trigger.to_state.attributes.friendly_name }} has left {{ trigger.zone.attributes.friendly_name }}

# Announce new devices on the network. Thanks to @robotsandcakes
  - alias: "Notify if New device connected"
    initial_state: 'on'
    trigger:
      - platform: event
        event_type: device_tracker_new_device
    action:
      - service: script.janet_speech_engine
        data:
          call_introduction: 1
        data_template:
          CustomMessage: >
            New entity ID {{ trigger.event.data.entity_id }} and hostname {{ trigger.event.data.host_name }}

###### NOTIFY IF VACATION MODE toggled
  - alias: 'Notify Vacation Mode'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_boolean.vacation
    action:
      - service: script.janet_speech_engine
        data:
          call_greeting: 1
        data_template:
          CustomMessage: 'Vacation Mode is now {{states.input_boolean.vacation.state}}'

###### NOTIFY IF GUEST MODE toggled
  - alias: 'Notify Guest Mode'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_boolean.guest
    action:
      - service: script.janet_speech_engine
        data:
          call_greeting: 1
        data_template:
          CustomMessage: 'Guest Mode is now {{states.input_boolean.guest.state}}'

###### NOTIFY IF UPDATE IS AVAILABLE
##HOME-ASSISTANT
  - alias: 'notify if update available'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.ha_version
    action:
      - service: notify.discord
        data:
          target: !secret discord
          message: "Home Assistant {{ states('sensor.ha_version') }} for update."
      - service: persistent_notification.create
        data_template:
          title: Update Available
          message: "Home Assistant {{ states('sensor.ha_version') }} for update."
          notification_id: Update Available
##CUSTOM CARD/COMPONENT
#CHECK
  - alias: 'check if custom update available'
    initial_state: 'on'
    trigger:
      - platform: time_pattern
        minutes: '/30'
    action:
      - service: custom_updater.check_all
#NOTIFY
  - alias: 'notify if custom update available'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id:
          - sensor.custom_card_tracker
          - sensor.custom_component_tracker
    action:
      - service: notify.discord
        data:
          target: !secret discord
        data_template:
          message: "There are {{ states(trigger.entity_id) }} update(s) pending, for {{ state_attr(trigger.entity_id, 'has_update') }}"
      - service: persistent_notification.create
        data_template:
          title: Update Available
          message: "There are {{ states(trigger.entity_id) }} update(s) pending, for {{ state_attr(trigger.entity_id, 'has_update') }}"
          notification_id: Update Available
