################################################################
## Packages / Presence
################################################################
homeassistant:
  customize:
    # GOOGLE TRAVEL TIME SENSORS
    sensor.nicole_phone_to_home:
      friendly_name: 'Nicole Phone to Home'
      icon: mdi:car
    sensor.nicole_home_to_work:
      friendly_name: 'Nicole Home to Work'
      icon: mdi:car
    # OTHER
    sensor.life360_sensor:
      friendly_name: Life 360

    script.location:
      emulated_hue_hidden: false
      emulated_hue_name: "location"
      friendly_name: Location

google_assistant:
  entity_config:
    script.location:
      expose: true
      name: 'location'

automation:
  - alias: house_mode_away
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: group.justin, group.nicole, input_boolean.guest
    action:
      - service_template: >
          {% if states.group.justin.state == 'off' and states.group.nicole.state == 'off' and states.input_boolean.guest.state == 'off' and states.input_boolean.away.state == 'off' %} input_boolean.turn_on
          {% elif states.group.justin.state == 'on' or states.group.nicole.state == 'on' or states.input_boolean.guest.state == 'on' and states.input_boolean.away.state == 'on' %} input_boolean.turn_off
          {% endif %}
        entity_id: input_boolean.away
      - service_template: >
          {% if states.input_boolean.away.state == 'on' %} script.house_mode_away
          {% endif %}
      - service_template: >
            {% if (as_timestamp(now()) - as_timestamp(states.input_boolean.away.last_changed)) < 60 %} notify.html5
            {% endif %}
        data_template:
          message: >
           {% if states.input_boolean.away.state == 'off' and states.input_boolean.guest.state == 'off' %} Alarm is disarmed, Welcome Home
           {% elif states.input_boolean.away.state == 'on' and states.input_boolean.guest.state == 'off' %} Alarm is armed, House set to Away Mode
           {% endif %}

  - alias: house_mode_vacation
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_boolean.away
        to: 'on'
        for:
          hours: 17
      - platform: state
        entity_id: input_boolean.away
        to: 'off'
    action:
      - service_template: >
          {% if states.input_boolean.vacation.state == 'off' and states.input_boolean.away.state == 'on' %} homeassistant.turn_on
          {% elif states.input_boolean.vacation.state == 'on' and states.input_boolean.away.state == 'off' %} homeassistant.turn_off
          {% endif %}
        entity_id: input_boolean.vacation
      - service: notify.html5
        data_template:
          message: >
           {% if states.input_boolean.vacation.state == 'off' %} Welcome Home I trust your time away was nice.
           {% elif states.input_boolean.vacation.state == 'on'%} Vacation Mode is now activated. Have a nice time away.
           {% endif %}

  - alias: house_mode_user_justin
    initial_state: 'on'
    trigger:
        - platform: state
          entity_id: device_tracker.justin_router
          to: 'not_home'
          for:
            minutes: 10
        - platform: state
          entity_id: device_tracker.justin_justin
    action:
      - service_template: >
          {% if states.device_tracker.justin_justin.state == 'home' or states.device_tracker.justin_router.state == 'home' and states.input_boolean.justin.state == 'off' %} homeassistant.turn_on
          {% elif states.device_tracker.justin_justin.state != 'home' or states.device_tracker.justin_router.state != 'home' and states.input_boolean.justin.state == 'off' and states.device_tracker.justin_justin.attributes.battery | int > 7 %} homeassistant.turn_off
          {% endif %}
        entity_id: input_boolean.justin

  - alias: house_mode_user_nicole
    initial_state: 'on'
    trigger:
        - platform: state
          entity_id: device_tracker.nicole_router
          to: 'not_home'
          for:
            minutes: 10
        - platform: state
          entity_id: device_tracker.nicole_nicole
    action:
      - service_template: >
          {% if states.device_tracker.nicole_nicole.state == 'home' or states.device_tracker.nicole_router.state == 'home' and states.input_boolean.nicole.state == 'off' %} homeassistant.turn_on
          {% elif states.device_tracker.nicole_nicole.state != 'home' or states.device_tracker.nicole_router.state != 'home' and states.input_boolean.nicole.state == 'off' and states.device_tracker.nicole_nicole.attributes.battery | int > 7%} homeassistant.turn_off
          {% endif %}
        entity_id: input_boolean.nicole

  - alias: 'welcome_home'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_boolean.away, input_boolean.vacation
        to: 'off'
    action:
# OUTDOOR PORCH LIGHT IS SET ON WHEN HOME FROM THEME PACKAGE
      - service_template: >
          {% if states.sensor.living_room_lux.state | float < 45 %}
          script.lr_concentrate
          {% endif %}
        entity_id: script.lr_concentrate
      - service: climate.set_away_mode
        data:
          entity_id: climate.hallway
          away_mode: 'false'

  # - alias: 'welcome_home_greeting'
  #   initial_state: 'on'
  #   trigger:
  #     - platform: state
  #       entity_id: device_tracker.justin_justin, device_tracker.nicole_nicole
  #       to: 'home'
  #   action:
  #     - wait_template: "{{ states.binary_sensor.door_front.state == 'on' }}"
  #     - service: script.janet_speech_engine
  #       data_template:
  #         person: >
  #           {%set nicole = states.device_tracker.nicole_nicole.state%}
  #           {%set nicole_ = states.device_tracker.nicole_nicole%}
  #           {%set justin = states.device_tracker.justin_justin.state%}
  #           {%set justin_ = states.device_tracker.justin_justin%}
  #           {%-if nicole != "home" and justin == "home"-%}
  #             Justin
  #           {%elif nicole == "home" and justin != "home"%}
  #             Nicole
  #           {%elif nicole == "home" and justin == "home" and (now() - nicole_.last_changed).total_seconds() < 600 and (now() - justin_.last_changed).total_seconds() < 600 %}
  #             Nicole and Justin
  #           {%elif nicole == "home" and justin == "home" and (now() - nicole_.last_changed).total_seconds() > 600 and (now() - justin_.last_changed).total_seconds() < 600 %}
  #             Justin
  #           {%elif nicole == "home" and justin == "home" and (now() - nicole_.last_changed).total_seconds() < 600 and (now() - justin_.last_changed).total_seconds() > 600 %}
  #             Nicole
  #           {%else%}
  #           {%endif%}
  #         message: >
  #           {{ ["Welcome back home PERSON",
  #               "Guess who is home. PERSON is!",
  #               "PERSON is now in the house.",
  #               "Welcome Home PERSON.  We have missed you. Or at least I did.",
  #               "Our home is now complete, Rest your head and relax your feet, Welcome Back PERSON",
  #               "Life is like a song, you’re back where you belong, Welcome home PERSON",
  #               "Hey there PERSON Welcome Home!",
  #               "Knock Knock. Who is There? PERSON is!",
  #               "PERSON, you are home!",
  #               "I know a secret. PERSON is home!"
  #              ] | random }}

script:
  location:
    sequence:
     - service: script.janet_speech_engine
       data:
         call_location_inquiry: 1
       data_template:
         person: >-
           {%set nicole = states.device_tracker.nicole_nicole.state%}
           {%set justin = states.device_tracker.justin_justin.state%}
           {%if nicole != "home" and justin == "home"%}
           nicole
           {%elif nicole == "home" and justin != "home"%}
           justin
           {%else%}
           {%endif%}

  house_mode_away:
    sequence:
      - service: light.turn_off
        data_template:
          entity_id: >
            {%- for state in states.light if state.entity_id != 'light.front_door' -%}
            {{- "," if not loop.first-}}{{ state.entity_id }}{{-endif-}}
            {%- endfor -%}
## this started turning off all my docker switches killing my whole system everytime we left the house!
      # - service: switch.turn_off
      #   data_template:
      #     entity_id: >
      #       {%- for state in states.switch if
      #       state.entity_id != 'switch.washing_machine' and
      #       state.entity_id != 'switch.dehumidifier' and
      #       state.entity_id != 'switch.office_powerbar' and
      #       state.entity_id != 'switch.pihole'-%}
      #       {{- "," if not loop.first-}}{{ state.entity_id }}{{-endif-}}
      #       {%- endfor -%}
      - service: media_player.turn_off
        data_template:
          entity_id: >
            {%- for state in states.media_player if
            state.entity_id != 'media_player.kodi_livingroom'-%}
            {{- "," if not loop.first-}}{{ state.entity_id }}{{-endif-}}
            {%- endfor -%}
      - service: climate.set_away_mode
        data:
          entity_id: climate.hallway
          away_mode: 'true'

sensor:
###### GOOGLE TRAVEL TIME
  - platform: google_travel_time
    name: Nicole Phone To Home
    api_key: !secret google_secret
    origin: device_tracker.nicole_nicole
    destination: zone.home

  - platform: life360
    username: !secret life360_username
    password: !secret life360_password
    mqtt_topic: "/life360/data"
    scan_interval: 60

###### MODES / PEOPLE
input_boolean:
  guest:
    name: Guest
    icon: mdi:account-box
    initial: off
  vacation:
    name: Vacation
    icon: mdi:sunglasses
    initial: off
  away:
    name: Away
    icon: mdi:account-off
    initial: off
  justin:
    name: Justin
    icon: mdi:account
  nicole:
    name: Nicole
    icon: mdi:account
  map_justin:
    name: map
    icon: mdi:map-search-outline
  map_nicole:
    name: map
    icon: mdi:map-search-outline
