################################################################
## Packages / Laundry Room
################################################################
homeassistant:
  customize:
###### Washing Machine ENERGY READINGS
    sensor.washing_machine_amps:
      friendly_name: "Amps"
      icon: mdi:power-plug
    sensor.washing_machine_watts:
      friendly_name: "Watts"
      icon: mdi:power-plug
    sensor.washing_machine_kw:
      friendly_name: "KW"
      icon: mdi:power-plug
    sensor.washing_machine_volts:
      friendly_name: "Volttage"
      icon: mdi:power-plug
    sensor.washing_machine_status:
      friendly_name: "Wash Status"
      icon: mdi:clipboard-outline
    switch.washing_machine:
      friendly_name: "Washing Machine"
      icon: mdi:washing-machine

sensor:
  ###### WASHING MACHINE ENERGY SENSORS
  - platform: template
    sensors:
      washing_machine_amps:
        #value_template: '{{ states.switch.washing_machine.attributes["current_a"] | replace(" A", "") | float }}'
        friendly_name_template: "{{ states.switch.washing_machine.name}} Current"
        value_template: '{{ states.switch.washing_machine.attributes["current_a"] | float }}'
        unit_of_measurement: 'A'
      washing_machine_watts:
        #value_template: '{{ states.switch.washing_machine.attributes["current_power_w"] | replace(" W", "") | float }}'
        friendly_name_template: "{{ states.switch.washing_machine.name}} Current Consumption"
        value_template: '{{ states.switch.washing_machine.attributes["current_power_w"] | float }}'
        unit_of_measurement: 'W'
      washing_machine_kw:
        #value_template: '{{ states.switch.washing_machine.attributes["total_energy_kwh"] | replace(" kW", "") | float }}'
        friendly_name_template: "{{ states.switch.washing_machine.name}} Total Consumption"
        value_template: '{{ states.switch.washing_machine.attributes["total_energy_kwh"] | float }}'
        unit_of_measurement: 'kW'
      washing_machine_volts:
        #value_template: '{{ states.switch.washing_machine.attributes["voltage"] | replace(" V", "") | float }}'
        friendly_name_template: "{{ states.switch.washing_machine.name}} Today's Consumption"
        value_template: '{{ states.switch.washing_machine.attributes["today_energy_kwh"] | float }}'
        unit_of_measurement: 'V'
      washing_machine_today_kwh:
        friendly_name_template: "{{ states.switch.washing_machine.name}} Today's Consumption"
        value_template: '{{ states.switch.washing_machine.attributes["today_energy_kwh"] | float }}'
        unit_of_measurement: 'kWh'

###### STATUS SENSORS
      washing_machine_status:
        value_template: >-
          {%- if states.sensor.washing_machine_watts.state|int <= 4.3 -%}
            Off
          {% else %}
            Running
          {% endif %}

automation:
  - alias: 'notify if washing machine is done'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.washing_machine_status
        from: 'Running'
        to: 'Off'
        for:
          minutes: 6
    action:
      - service: switch.turn_off
        entity_id: switch.washing_machine
      - service: script.laundry_tts

script:
  laundry_tts:
    sequence:
    - service: script.janet_speech_engine
      data:
        call_greeting: 1
        call_inform: 1
        CustomMessage: "The Washing machine has completed it's cycle."
