################################################################
## Packages / Master Bedroom
################################################################
homeassistant:
  customize:
    switch.white_noise:
      emulated_hue_hidden: false
      friendly_name: 'White Noise'
      icon: mdi:snowflake
    switch.bedroom_tv:
      friendly_name: TV
      icon: mdi:monitor
    switch.bedroom_fan:
      emulated_hue_hidden: false
      icon: mdi:fan
      friendly_name: Bedroom Fan
    switch.bedroom_lamps:
      emulated_hue_hidden: false
      icon: mdi:lamp
      friendly_name: Bedroom Lamp
    #Bedroom computer Switch
    switch.bedroom_media:
      emulated_hue_hidden: false
      icon: mdi:monitor
      friendly_name: Bedroom Media
    #Motion Sensor
    binary_sensor.room_masterbed_motion:
      friendly_name: "Master Bed"
    sensor.master_bed_temperature:
      friendly_name: "Master Bed"

sensor:
  - platform: template
    sensors:
      white_noise:
        value_template: >-
          {% set state = states.media_player.master_bedroom_speaker.attributes.media_content_id%}
          {% set object = "http://192.168.1.115/white_noise/blizzard.mp3" %}
          {% if state == object %}on{% else %}off{% endif %}

switch:
###### Switch for White Noise
  - platform: template
    switches:
      white_noise:
        value_template: '{{ states.sensor.white_noise.state }}'
        turn_on:
          service: script.turn_on
          entity_id: script.white_noise
        turn_off:
          service: media_player.turn_off
          entity_id: media_player.master_bedroom_speaker

  - platform: template
    switches:
      bedroom_media:
        value_template: '{{ states.sensor.bedroom_pc_status.state }}'
        turn_on:
          service: script.turn_on
          entity_id: script.bedroom_media_on
        turn_off:
          service: script.turn_on
          entity_id: script.bedroom_media_off

script:
  bedroom_media_on:
    sequence:
      - service: switch.turn_on
        entity_id: switch.bedroom_tv
      - delay: '00:00:10'
      - delay: '00:00:05'
      - service: shell_command.bedroom_tv_cec

  bedroom_media_off:
    sequence:
      - service: switch.turn_off
        entity_id: switch.bedroom_tv

  white_noise:
    sequence:
      - service: media_player.volume_set
        data:
          entity_id: media_player.master_bedroom_speaker
          volume_level: 0.5
      - service: media_player.play_media
        data:
          entity_id: media_player.master_bedroom_speaker
          media_content_id: "http://192.168.1.115/white_noise/blizzard.mp3"
          media_content_type: "audio/mp3"
