################################################################
## Packages / Nursery
################################################################
homeassistant:
  customize:
    switch.office_lightswitch:
      friendly_name: Nursery Light Switch
      icon: mdi:lightbulb

light:
  - platform: nanoleaf_aurora
    name: aurora
    host: 192.168.1.101
    token: !secret nanoleaf

sensor:
  - platform: template
    sensors:
      white_noise_nursery:
        value_template: >-
          {% set state = states.media_player.nursery_speaker.attributes.media_content_id%}
          {% set object = "http://192.168.1.115/white_noise/blizzard.mp3" %}
          {% if state == object %}on{% else %}off{% endif %}

switch:
###### Switch for White Noise
  - platform: template
    switches:
      white_noise_nursery:
        value_template: '{{ states.sensor.white_noise_nursery.state }}'
        turn_on:
          service: script.turn_on
          entity_id: script.white_noise_nursery
        turn_off:
          service: media_player.turn_off
          entity_id: media_player.nursery_speaker

script:
  white_noise_nursery:
    sequence:
      - service: media_player.volume_set
        data:
          entity_id: media_player.nursery_speaker
          volume_level: 0.5
      - service: media_player.play_media
        data:
          entity_id: media_player.nursery_speaker
          media_content_id: "http://192.168.1.115/white_noise/blizzard.mp3"
          media_content_type: "audio/mp3"

  nurse:
    sequence:
      - service: switch.turn_off
        data:
          entity_id: switch.office_lightswitch
      - service: switch.turn_on
        data:
          entity_id: switch.white_noise_nursery
      - service: light.turn_on
        data:
          entity_id: light.aurora
          brightness: 70
          effect: 'Flames'
automation:
  - alias: 'nursery_switch_1'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.findlay_s_room
    condition:
      - condition: state
        entity_id: sensor.findlay_s_room
        state: '1_click_up'
    action:
      - service: switch.toggle
        data:
          entity_id: switch.office_lightswitch

  - alias: 'nursery_switch_2'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.findlay_s_room
    condition:
      - condition: state
        entity_id: sensor.findlay_s_room
        state: '2_click_up'
    action:
      - service: light.toggle
        data:
          entity_id: light.aurora

  - alias: 'nursery_switch_3'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.findlay_s_room
    condition:
      - condition: state
        entity_id: sensor.findlay_s_room
        state: '3_click_up'
    action:
      - service: switch.toggle
        data:
          entity_id: switch.white_noise_nursery

  - alias: 'nursery_switch_4'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.findlay_s_room
    condition:
      - condition: state
        entity_id: sensor.findlay_s_room
        state: '4_click_up'
    action:
      - service: switch.turn_off
        data:
          entity_id: switch.white_noise_nursery, switch.office_lightswitch
      - service: light.turn_off
        data:
          entity_id: light.aurora
