################################################################
## Packages / Findlays Room
################################################################
homeassistant:
  customize:
    automation.light_finn_sleep:
      friendly_name: 'Keep Light Off'
      icon: mdi:brightness-4
    automation.finn_temp_watchdog:
      friendly_name: 'Temperature Watch Dog'
      icon: mdi:thermometer-lines
    switch.sleep_finn:
      emulated_hue_hidden: false
      google_assistant: true
      google_assistant_name: "Sleep"
      friendly_name: 'Sleep'
      icon: mdi:sleep

automation:
  - alias: 'finn_temp_watchdog'
    initial_state: 'on'
    trigger:
      - platform: numeric_state
        entity_id: sensor.findlay_room_temperature
        below: 19
    condition:
      - condition: state
        entity_id: 'input_boolean.finn_sleep'
        state: 'on'
    action:
      - service: climate.set_temperature
        data_template:
          entity_id: climate.hallway
          temperature: "{{ (states.climate.hallway.attributes.current_temperature | float) +0.5 }}"

  - alias: 'light_finn_sleep'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_boolean.finn_sleep
        to: 'on'
      - platform: template
        value_template: "{% if is_state('light.findlay_s_room', 'on') %}true{% endif %}"
    condition:
      - condition: state
        entity_id: 'input_boolean.finn_sleep'
        state: 'on'
    action:
      - service: light.turn_off
        data:
          entity_id: light.findlay_s_room
      - service: media_player.volume_set
        data:
          entity_id: media_player.findlays_speaker
          volume_level: 0.5
      - service: media_player.play_media
        data:
          entity_id: media_player.findlays_speaker
          media_content_id: "http://192.168.1.115/white_noise/blizzard.mp3"
          media_content_type: "audio/mp3"

  - alias: 'light_finn'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_boolean.finn_sleep
        to: 'off'
      - platform: state
        entity_id: sensor.findlay_room_motion
        to: 'True'
      - platform: numeric_state
        entity_id: 'sensor.findlay_room_lux'
        below: 45
    condition:
      - condition: numeric_state
        entity_id: 'sensor.findlay_room_lux'
        below: 45
      - condition: state
        entity_id: 'input_boolean.finn_sleep'
        state: 'off'
      - condition: state
        entity_id: sensor.findlay_room_motion
        state: 'True'
    action:
      - service: light.turn_on
        data_template:
          entity_id: light.findlay_s_room
          brightness: >
            {% if (as_timestamp(now()) - as_timestamp(states.input_boolean.finn_sleep.last_changed)) > 600 %} 250
            {% else %}
            100
            {% endif %}

  - alias: 'light_finn_off'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.findlay_room_motion
        to: 'False'
        for:
          minutes: 3
      - platform: numeric_state
        entity_id: 'sensor.findlay_room_lux'
        above: 45
    action:
      - service: light.turn_off
        data:
          entity_id: light.findlay_s_room

switch:
###### Switch for Sleep Mode
  - platform: template
    switches:
      sleep_finn:
        value_template: '{{ states.input_boolean.finn_sleep.state }}'
        turn_on:
          - service: input_boolean.turn_on
            entity_id: input_boolean.finn_sleep
          - service: input_boolean.turn_off
            entity_id: input_boolean.janet_speech_notifications
        turn_off:
          - service: input_boolean.turn_off
            entity_id: input_boolean.finn_sleep
          - service: input_boolean.turn_on
            entity_id: input_boolean.janet_speech_notifications
          - service: media_player.turn_off
            entity_id: media_player.findlays_speaker

input_boolean:
  finn_sleep:
    name: 'Sleep'
    icon: mdi:sleep
