################################################################
## Packages / Office
################################################################
homeassistant:
  customize:
    #Office computer Switch
    switch.office_pc:
      icon: mdi:monitor
      friendly_name: PC
    switch.office_powerbar:
      icon: mdi:power
      friendly_name: Power Strip

switch:
###### SONOFF POW POWERBAR
  - platform: mqtt
    name: "Office PowerBar"
    state_topic: "stat/office_pwrbar/POWER"
    command_topic: "cmnd/office_pwrbar/POWER"
    payload_on: "ON"
    payload_off: "OFF"
    optimistic: false
    qos: 0
    retain: true

  - platform: template
    switches:
      office_pc:
        value_template: "{{ states.sensor.office_draw.state|int > 100 }}"
        turn_on:
          service: script.office_pc_on
        turn_off:
          service: script.office_pc_off

sensor:
###### STEAM COMPONENT
  - platform: steam_online
    api_key: !secret steam_api
    accounts:
      - id: !secret steam_user
        entity_id: "account"

###### SONOFF POW SENSORS
  - platform: mqtt
    name: "Office Draw"
    state_topic: "tele/office_pwrbar/ENERGY"
    qos: 0
    unit_of_measurement: "W"
    value_template: "{{ value_json.Power }}"

  - platform: mqtt
    name: "Office Voltage"
    state_topic: "tele/office_pwrbar/ENERGY"
    qos: 0
    unit_of_measurement: "V"
    value_template: "{{ value_json.Voltage }}"

  - platform: mqtt
    name: "Office Today"
    state_topic: "tele/office_pwrbar/ENERGY"
    qos: 0
    unit_of_measurement: "kWh"
    value_template: "{{ value_json.Today }}"

  - platform: mqtt
    name: "Office Current"
    state_topic: "tele/office_pwrbar/ENERGY"
    qos: 0
    unit_of_measurement: "A"
    value_template: "{{ value_json.Current }}"

  - platform: mqtt
    name: "Office Yesterday"
    state_topic: "tele/office_pwrbar/ENERGY"
    qos: 0
    unit_of_measurement: "kWh"
    value_template: "{{ value_json.Yesterday }}"

###### POWER & RESET SWITCH ON PC CASE ROUTED TO WEMOS D1 MINI
binary_sensor:
  - platform: mqtt
    name: "Office Reset Button"
    state_topic: "Office_PC_Buttons/Switch/Switch_2"
    qos: 0
    payload_on: 1
    payload_off: 0

  - platform: mqtt
    name: "Office Power Button"
    state_topic: "Office_PC_Buttons/Switch/Switch_1"
    qos: 0
    payload_on: 1
    payload_off: 0

automation:
  # - alias: office_reset_button
  #   initial_state: 'on'
  #   trigger:
  #     - platform: state
  #       entity_id: binary_sensor.office_reset_button
  #       from: 'off'
  #       to: 'on'
  #   action:
  #     - service: switch.toggle
  #       entity_id: switch.led_strip
  #     - service_template: >
  #         {% if states.light.hue_go.state == 'off' %} script.office_hue_go_on
  #         {% elif states.light.hue_go.state == 'on' %} script.office_hue_go_off
  #         {% endif %}
  #     - service: light.toggle
  #       entity_id: light.aurora

  - alias: office_power_button
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.office_power_button
        from: 'off'
        to: 'on'
    action:
      - service: switch.toggle
        entity_id: switch.office_pc

script:
  office_pc_on:
    sequence:
    - service: mqtt.publish
      data:
        topic: "cmnd/office_pwrbar/TelePeriod"
        payload: "10"
    - service: switch.turn_on
      entity_id: switch.office_powerbar
    - delay: '00:00:03'
    - service: shell_command.office_relay_1
    - service: shell_command.office_relay_0
    - delay: '00:00:10'
    - service: mqtt.publish
      data:
        topic: "cmnd/office_pwrbar/TelePeriod"
        payload: "1"
  office_pc_off:
    sequence:
    - service: shell_command.office_relay_1
    - service: shell_command.office_relay_0
    - delay: '00:00:08'
    - service: shell_command.office_relay_1
    - service: shell_command.office_relay_0
    - service: mqtt.publish
      data:
        topic: "cmnd/office_pwrbar/TelePeriod"
        payload: "10"
    - wait_template: "{{ states.sensor.office_draw.state|int < 100 }}"
    - service: switch.turn_off
      entity_id: switch.office_powerbar
    - service: mqtt.publish
      data:
        topic: "cmnd/office_pwrbar/TelePeriod"
        payload: "1"

shell_command:
  office_relay_0: !secret office_relay_0
  office_relay_1: !secret office_relay_1
