################################################################
## Packages / Sensors
################################################################
homeassistant:

###### BINARY SENSORS ------------------------------------------
binary_sensor:
  - platform: workday
    country: CA
###### SENSORS -------------------------------------------------
sensor:
  - platform: huesensor
### tautulli and plex monitor
  - platform: tautulli
    api_key: !secret tautulli_api
    host: !secret tautulli_host
  - platform: template
    sensors:
      tautulli_lan:
        friendly_name: "tautulli_lan"
        entity_id: sensor.tautulli
        unit_of_measurement: 'Mbps'
        value_template: "{{states.sensor.tautulli.attributes.lan_bandwidth|float / 1000}}"
      tautulli_wan:
        friendly_name: "tautulli_wan"
        entity_id: sensor.tautulli
        unit_of_measurement: 'Mbps'
        value_template: "{{states.sensor.tautulli.attributes.wan_bandwidth|float / 1000}}"
      tautulli_total:
        friendly_name: "tautulli_total"
        entity_id: sensor.tautulli
        unit_of_measurement: 'Mbps'
        value_template: "{{states.sensor.tautulli.attributes.total_bandwidth|float / 1000}}"
### SCRAPE CURRENT ENERGY TIER
  - platform: command_line
    name: Electricity Price
    command: !secret energy_scrape_url
    value_template: "{{value.split('>')[4]|replace('&cent;/kWh</span','')}}"
    unit_of_measurement: "¢/kWh"
    scan_interval: 600

###### AVERAGE TEMPERATURE
  - platform: min_max
    type: mean
    name: Average Whole Home
    entity_ids:
      - sensor.hallway_thermostat_temperature
      - sensor.findlay_room_temperature
      - sensor.living_room_temperature
      - sensor.dining_room_temperature

###### DATE TIME
  - platform: yr
  - platform: time_date
    display_options:
      - "date_time"
      - 'time'

###### DAY OF THE WEEK
  - platform: template
    sensors:
      date_weekday:
        entity_id: sensor.date
        value_template: "{{as_timestamp(now())|timestamp_custom('%A', True)}}"

###### MONTH OF THE YEAR
  - platform: template
    sensors:
      date_month:
        entity_id: sensor.date
        value_template: "{{as_timestamp(now())|timestamp_custom('%B', True)}}"
