################################################################
## Packages / Waste Pickup
################################################################
homeassistant:
  customize:
    sensor.waste_pickup_garbage_recycling:
      friendly_name: Waste Pickup
      icon: mdi:delete
    sensor.waste_pickup_yard_waste:
      friendly_name: Yard Waste Pickup
      icon: mdi:delete
    sensor.waste_pickup_container:
      friendly_name: 3 Container Exemption
      icon: mdi:delete
    script.garbage_tracker:
      friendly_name: Garbage Tracker
      emulated_hue_hidden: false

google_assistant:
  entity_config:
    script.garbage_tracker:
      expose: true
      name: 'Garbage Tracker'

sensor:
######  GARBAGE AND RECYCLE
  - platform: command_line
    command: "cat /config/www/waste_pickup_garbage_recycle.txt"
    name: 'Waste Pickup Garbage Recycling'
    scan_interval: 43200
    value_template: '{{value | int | timestamp_custom("%A %B %d", true)}}'
######  YARD WASTE
  - platform: command_line
    command: "cat /config/www/waste_pickup_yard_waste.txt"
    name: 'Waste Pickup Yard Waste'
    scan_interval: 43200
    value_template: '{{value | int | timestamp_custom("%A %B %d", true)}}'
######  3 Container Exemption
  - platform: command_line
    command: "cat /config/www/waste_pickup_container.txt"
    name: 'Waste Pickup Container'
    scan_interval: 43200
    value_template: '{{value | int | timestamp_custom("%A %B %d", true)}}'
###### TTS SCRIPT TO CALL FROM ALEXA
script:
  garbage_tracker:
    sequence:
      - service: script.janet_speech_engine
        data:
          call_greeting: 1
          call_inform: 1
        data_template:
          CustomMessage: >-
            {%- if as_timestamp(now())|timestamp_custom('%A %B %d', True) == states.sensor.waste_pickup_garbage_recycling.state -%}
            The garbage is to go out this evening.
            {%-else-%}
            {{' '}}The next garbage pickup is on {{states('sensor.waste_pickup_garbage_recycling')}}.{{' '}}
            {%-endif-%}
